import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased flex flex-col min-h-screen text-4xl`}
      >
        <header>
          <h1>Stonehaus</h1>
        </header>
        <main className="grow">{children}</main>
        <footer>
          <p>&copy; 2026 Stonehaus. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
