import type { Metadata } from "next";
import { inter, bricolage_grotesque } from "./fonts";
import "./globals.css";
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolage_grotesque.variable} ${inter.variable} antialiased scroll-smooth flex flex-col min-h-screen`}
      >
        <main className="grow">{children}</main>
        <footer>
          <p>&copy; 2026 Stonehaus. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
